name: Code Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CLICOLOR_FORCE: 1

jobs:
  build:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Sync dependencies
        run: uv sync --dev
      - name: Ruff Check
        uses: astral-sh/ruff-action@v3
      - name: Ty Lint
        run: uvx ty check --output-format=github
